name: ci workflow for java
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
     # fail-fast: false
    steps:
      - name: checkout the code 
        uses: actions/checkout@v4

      - name: set-up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      
      #- name: build package
      #  run: mvn clean package -DskipTests
      
      #- name: build test results
       # run: mvn test
      
      - name: Build and Test
        run: mvn clean package
        
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-app-jar
          path: target/*.jar
